services:
  - type: web
    name: kritika-ecommerce
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:8080 main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "0"
